Repository radical-cybertools/radical.analytics, pull requests merged in 2019-02, with the labels that each got.

#74 Fix/issue 73
  src/radical/analytics/session.py
Labels: layer:analytics, layer:rp, layer:utils, priority:high, topic:performance, type:feature

#88 Feature/utilization
  src/radical/analytics/session.py
Labels: priority:medium, topic:api, topic:data, type:feature

#90 add allocation plot script
  examples/09_core_allocation_plot.py
Labels: priority:medium, topic:data, type:documentation, type:feature

#87 Feature/plotter
  src/radical/analytics/plotter.py
Labels: priority:medium, topic:api, topic:data, type:feature
