Repository radical-cybertools/radical.analytics, pull requests merged in 2020-06, with the labels that each got.

#115 matplotlib 3.0.1+ requirement because of bugs e.g. failed to import g…
  setup.py
Labels: priority:high

#122 Fix/plot origin
  bin/radical-analytics-check
  bin/radical-analytics-plot.py
  bin/rp_inspect/plot_util.py
  src/radical/analytics/entity.py
  src/radical/analytics/session.py
Labels: priority:high, topic:data, type:bug, type:feature

#125 Fix/concurrency
  bin/rp_inspect/plot_conc.py
  src/radical/analytics/session.py
Labels: priority:medium, topic:enhancement, type:enhancement
