Repository radical-cybertools/radical.analytics, pull requests merged in 2021-06, with the labels that each got.

#142 install style into share/
  setup.py
  src/radical/analytics/__init__.py
  styles/radical_mpl.txt
Labels: priority:medium, type:enhancement

#141 Fix/filter
  tests/example-data/unit-entity-example.json
Labels: priority:low, type:enhancement

#140 Fix/ns index
  setup.py
  src/radical/__init__.py
Labels: priority:low, type:enhancement

#143 Matplotlib style and plot size for latex
  docs/source/index.rst
  docs/source/plotting.rst
  setup.py
  src/radical/analytics/__init__.py
  src/radical/analytics/utils/__init__.py
  src/radical/analytics/utils/plot.py
  styles/radical_mpl.txt
Labels: priority:high, topic:data, type:feature
