Repository radical-cybertools/radical.analytics, pull requests merged in 2021-07, with the labels that each got.

#135 add new resource util plot type
  .flake8
  .pylintrc
  bin/radical-analytics-check
  bin/radical-analytics-inspect
  bin/radical-analytics-plot.py
  bin/rp_inspect/plot_conc.py
  bin/rp_inspect/plot_dur.py
  bin/rp_inspect/plot_rate.py
  bin/rp_inspect/plot_state.py
  bin/rp_inspect/plot_util.py
  bin/rp_inspect/plot_util_2.py
  docs/source/duration.rst
  docs/source/images/ru_v1.png
  docs/source/images/ru_v1_multi.png
  docs/source/images/ru_v2.png
  docs/source/index.rst
  docs/source/inspection.rst
  docs/source/installation.rst
  docs/source/introduction.rst
  docs/source/metrics.md
  docs/source/plotting.rst
  docs/source/utilization.rst
  src/radical/analytics/__init__.py
  src/radical/analytics/entity.py
  src/radical/analytics/experiment.py
  src/radical/analytics/session.py
  src/radical/analytics/utils/__init__.py
  src/radical/analytics/utils/plot.py
  styles/radical_mpl.txt
Labels: priority:medium, type:feature

#151 nbsphinx
  .readthedocs.yml
  docs/source/conf.py
  docs/source/duration.rst
  docs/source/durations.ipynb
  docs/source/index.rst
  docs/source/requirements.txt
  docs/source/sessions/re.session.login1.lei.018775.0004.tar.bz2
  docs/source/sessions/re.session.login1.lei.018775.0005.tar.bz2
  docs/source/sessions/re.session.login1.lei.018775.0007.tar.bz2
  docs/source/sessions/re.session.login1.lei.018775.0008.tar.bz2
  docs/source/utilization.ipynb
  docs/source/utilization.rst
  src/radical/analytics/__init__.py
  src/radical/analytics/session.py
  src/radical/analytics/utils/__init__.py
  src/radical/analytics/utils/plot.py
Labels: priority:high, type:documentation

#152 Duration distributions and theme
  docs/source/apidoc.rst
  docs/source/conf.py
  docs/source/duration.ipynb
  docs/source/index.rst
  docs/source/requirements.txt
  docs/source/utilization.ipynb
  src/radical/analytics/utils/plot.py
Labels: priority:medium, type:documentation

#154 Time stamps and concurrency analyses + inspection
  docs/source/concurrency.ipynb
  docs/source/concurrency.rst
  docs/source/duration.ipynb
  docs/source/index.rst
  docs/source/inspection.ipynb
  docs/source/inspection.rst
  docs/source/installation.rst
  docs/source/plotting.rst
  docs/source/timestamps.ipynb
  docs/source/utilization.ipynb
  styles/radical_mpl.txt
Labels: priority:medium, type:documentation
